### ISSUE TITLE
Allow custom stellar model?

### ISSUE THREAD

**Issue by sebastian-zieba** [Exo-TiC/ExoTiC-LD#21]
Hi, I was wondering if there are any plans to give the user the possibility to use their own stellar models. I saw that there’s already a way to use your own custom throughput. I guess if you also allowed custom stellar models, the user wouldn’t need to download the accompanying data on Zenodo at all?
By the way, this is a great tool!! Thank you for putting it open-source!

**Comment by hrwakeford** [comment]
That is a great Idea I will add this to the list of enhancements for the code.
