### ISSUE TITLE
Consider adding support for HST STIS G750M instrument mode

### ISSUE THREAD

**Issue by andreok** [Exo-TiC/ExoTiC-LD#37]

**Comment by hrwakeford** [comment]
To run exotic-ld for an instrument mode not currently listed in the documentation you can input the throughput/sensitivity profile as a custom file. You can find the custom_throughput tutorial here [https://exotic-ld.readthedocs.io/en/latest/views/tutorials/custom_throughput.html](https://exotic-ld.readthedocs.io/en/latest/views/tutorials/custom_throughput.html )

If you would like to provide a throughput file for STIS G750M for us to add to the supported instruments list please send us one either by attaching it to this issue or via email.

**Comment by hrwakeford** [comment]
Issue closed with suggestion to supply needed file or use the software "custom" functionality to use for STIS G750M datasets.
