### ISSUE TITLE
Add in JWST mode sensitivity files

### ISSUE THREAD

**Issue by hrwakeford** [Exo-TiC/ExoTiC-LD#5]
Add in ability to run limb-darkening for the following modes:

- [x] NIRCam F322W2
- [x] NIRCam F444
- [x] NIRISS SOSS order 1
- [x] NIRISS SOSS order 2
- [x] NIRSpec G140H/M f100lp
- [x] NIRSpec G140M/H f070lp
- [x] NIRSpec G235H/M f170lp
- [x] NIRSpec G395H/M f290lp
- [x] NIRSpec Prism
- [x] MIRI LRS
- [x] HST WFC3 UVIS G280 -1 spectral order

**Comment by hrwakeford** [comment]
At some point we will also want to convert the sensitivity files from IDL .sav files to something more appropriate for Python

- suggestions welcomed to the file format for these

**Comment by natashabatalha** [comment]
Here is how you would do that with PandExo

```
import pandexo.engine.justdoit as jdi
import pandas as pd

#get all instruments
inst = jdi.print_instruments()
#omit WFC3
jwst = list(inst)[1:]
#save all as dictionaries
thrus = {}
for i in jwst:
    if 'SOSS' in i: 
        thrus[i+'O1'] = jdi.get_thruput(i,niriss=1)
        pd.DataFrame(thrus[i+'O1']).to_csv(i+' O1.csv')
        thrus[i+'O2'] = jdi.get_thruput(i,niriss=2)
        pd.DataFrame(thrus[i+'O2']).to_csv(i+' O2.csv')
    else:
        thrus[i] = jdi.get_thruput(i)
        pd.DataFrame(thrus[i]).to_csv(i+'.csv')
    
```

**Comment by hrwakeford** [comment]
Amazing thank you @natashabatalha I will get these incorporated ASAP
using [PandExo](https://github.com/natashabatalha/PandExo )

**Comment by hrwakeford** [comment]
While working on this issue it has been found that the G750L and G750M sensitivity files did not read in correctly. 

In addition the following things will be done to improve the consistency of the code:

- Update all of the current sensitivity files to csv files 
- Make sure all files are in angstroms for wavelength and percentage for throughput/sensitivity
- Use consistent and clear file names
- Make a figure showing all of the throughputs that are available in the code and a gallery of each individual file

**Comment by hrwakeford** [comment]
<img width="914" alt="Screenshot 2022-03-04 at 13 49 56" src="https://user-images.githubusercontent.com/7988823/156775028-9d1d56aa-c936-46cb-a6e9-bb77015bf526.png">

**Comment by natashabatalha** [comment]
As requested, here are updates to PCE files with Pandeia 2. 

![thruputs](https://user-images.githubusercontent.com/6554465/212397996-84404a29-27c3-4e32-88f2-b2367152eeee.png)

[UpdatedPandeia2.zip](https://github.com/Exo-TiC/ExoTiC-LD/files/10414625/UpdatedPandeia2.zip)
