### ISSUE TITLE
Corrupted phoenix spectra files

### ISSUE THREAD

**Issue by ben-cassese** [Exo-TiC/ExoTiC-LD#55]
Hello, and congrats on the recent JOSS acceptance! This looks like a great package and I'm looking forward to using it in my research 🙂 

I noticed that a handful of the phoenix spectra hosted [online](https://www.star.bris.ac.uk/exotic-ld-data/) seem to have been corrupted. I found eight in total:

- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.5/teff6900/logg5.0/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.5/teff6700/logg2.5/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.5/teff6700/logg4.0/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.5/teff6700/logg5.0/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.5/teff6700/logg5.5/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.0/teff2600/logg0.0/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-0.5/teff2500/logg0.0/phoenix_spectra.dat
- https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-0.5/teff2400/logg5.5/phoenix_spectra.dat

Most of these are missing the first header line (which disrupts the `skiprows` [here](https://github.com/Exo-TiC/ExoTiC-LD/blob/f03c665a942fcaab02c9ab6c0d34c17f175fe9af/exotic_ld/ld_grids.py#L258-L259)) though the last one seems to be missing data. When creating a `StellarLimbDarkening` object that relies on any of these files, it fails the `StellarLimbDarkening._check_stellar_model()` method that's called during `__init__`. For example:

```python
sld = StellarLimbDarkening(
    M_H=-1.5,
    Teff=6900,
    logg=5.0,
    ld_model="phoenix",
    ld_data_path=EXOTIC_LD_PATH,
    interpolate_type="nearest",
    verbose=2,
)
```

produces the output that ends in an error message:

> Input stellar parameters are M_H=-1.5, Teff=6900, logg=5.0.
Loading stellar model from phoenix grid.
Using interpolation type = nearest.
Exact match found with M_H=-1.5, Teff=6900.0, logg=5.0.
Downloading https://www.star.bris.ac.uk/exotic-ld-data/phoenix/MH-1.5/teff6900/logg5.0/phoenix_spectra.dat: 100%|██████████| 81.0M/81.0M [00:53<00:00, 1.60MiB/s]
Downloaded ExoTic_LD_data/phoenix/MH-1.5/teff6900/logg5.0/phoenix_spectra.dat.
Stellar model loaded.
```python
ValueError: mu values must have the same shape as stellar_intensities.shape[1].
```

I think these are the only spectra files with issues since all of the others (phoenix and the other grids) passed that check, but I didn't do any tests for problems that wouldn't be caught by that initial shape comparison. It'd be great if either these files could be fixed, or if their leaves could be removed from the phoenix KD tree. Thanks again!

**Comment by ben-cassese** [comment]
Hi! Just wanted to check in on this and see if it would be possible to fix these reference files.

**Comment by DavoGrant** [comment]
@ben-cassese absolutely wicked find! Really appreciate you finding and reporting this. So sorry for the delay on my part -- occupational changes have prevented me from keeping up with things. 

I have rebuilt the above mentioned files, and they are now live on the data sever. NB. I have not been able to reproduce the corruption (although some of the original phoenix files have truncated wavelengths it seems). Do let me know if you find any further issues. I'll close this one for now.
